app/routes/frames.py
import os

from app import db
from app.models import Frame, Label, Word
from datetime import datetime
from flask_login import login_required, current_user
from flask import Blueprint,render_template, request, flash, jsonify, redirect, url_for,send_from_directory

# create Blueprint
frames = Blueprint('frames', __name__)

FRAME_FOLDER = 'app/datasets/frames/'

# Custom static data
@frames.route('/frames_datasets/<foldername>/<path:filename>')
def frames_datasets(foldername, filename):
  return send_from_directory('datasets/frames/'+foldername+'/', filename)

@frames.route('/frame-edit/<video_id>', methods=['GET','POST'])
@login_required
def frame_edit(video_id):
  if request.method == 'GET':
    # get label data
    labels = Label.query.order_by(Label.label.asc()).all()
    words = Word.query.order_by(Word.word.asc()).all()      
    #get frame data
    frames = Frame.query.filter(Frame.video_id==video_id).all()
    return render_template('frames/edit.html', frames=frames ,labels=labels, words=words, user=current_user)
  else:
    labels = request.form.getlist('label')
    labels_id = request.form.getlist('label_id')
    words = request.form.getlist('word')
    words_id = request.form.getlist('word_id')
    ids = request.form.getlist('id')
    index = 0
    for label_id in labels_id:
      frame = Frame.query.get(ids[index])
      # frame.label = label
      frame.label_id = label_id
      # frame.word = words[index]
      frame.word_id = words_id[index]
      frame.updated_at = datetime.now().replace(microsecond=0)
      db.session.commit()
      index += 1
  return redirect(url_for('videos.videos_list'))
  

app/templates/frames/edit.html
{% extends "base.html" %}

{%block title %}
Frames
{% endblock %}

{% block content %}
<div class="container">
  <div class="card bg-light shadow">
    <div class="card-header bg-success text-light">
      <strong>Video {{frames[0].folder}}.mp4 Frames List</strong>
    </div>
    <div class="card-body ">
      <form method="POST"  action="/frame-edit/{{frames[0].video_id}}">
        <div class="mb-3">
          <a class="btn btn-sm btn-secondary" role="button" href="/video-list">
            Back</a>
          <button type="submit" class="btn btn-sm btn-primary">Edit Frame</button>
        </div>
        <table class="table table-sm">
          <thead>
            <tr class="table-primary">
              <th width="40" class="text-center">#</th>
              <th width="250" class="text-center">Folder Name</th>
              <th width="250" class="text-center">Image Name</th>
              <th width="200" class="text-center">Updated At</th>
              <th class="text-center">Image</th>
              <th width="150" class="text-center">Label</th>
              <th width="150" class="text-center">Word</th>
            </tr>
          </thead>
          <tbody>
            {% set count = namespace(value=1) %}
            {% set class = "table-default" %}
            {% for frame in frames %}
              <tr>
                <td class="text-center">{{ count.value }}.</td>
                <td>{{ frame.folder }} </td>
                <td>{{ frame.image_name }} {{ frame.id }}</td>
                <td class="text-center">{{ frame.updated_at }}</td>
                <td class="text-center">
                  <image class="img-thumbnail" width="120"
                    src="{{ url_for('frames.frames_datasets',
                    foldername=frame.folder, filename=frame.image_name) }}"
                    data-my-var="{{ url_for('frames.frames_datasets',
                    foldername=frame.folder, filename=frame.image_name) }}" >
                  </image>
                </td>
                <td>
                  <select class="form-control" name="label_id">
                    <option value=""></option>
                  {% for label in labels %}
                    <option value="{{ label.id }}"
                      {{ "selected" if label.id==frame.label_id }}>{{ label.label }}</option>
                  {% endfor %}
                  </select>
                </td>
                <td>
                  <select class="form-control" name="word_id">
                    <option value=""></option>
                  {% for word in words %}
                    <option value="{{ word.id }}"
                      {{ "selected" if word.id==frame.word_id }}>{{ word.word }}</option>
                  {% endfor %}
                  </select>
                  <input type="hidden" class="form-control" name="id" value="{{ frame.id }}">
                </td>
              </tr>
              {% set count.value = count.value + 1 %}
            {% endfor%}
          </tbody>
        </table>
        <div class="mb-3">
          <a class="btn btn-sm btn-secondary" role="button" href="/video-list">
            Back</a>
          <button type="submit" class="btn btn-sm btn-primary">Edit Frame</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- The Modal -->
<div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Frame</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>

      <!-- Modal body -->
      <div class="modal-body text-center">
        <div class="embed-responsive embed-responsive-16by9">
          <image id="frame" src="" width="320">
          </image>
        </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>
{% endblock%}